### ISSUE TITLE
Fast incremental update with occasional reindexing

### ISSUE THREAD

**Issue by npip99** [timescale/pgvectorscale#129]
I'm not sure if I'm missing something in the documentation, but how do we periodically reindex new embeddings? Having a diskann index makes "INSERT" incredibly slow.

This is the behavior that I observe:

## Initial Index

```sql
CREATE INDEX ix_chunk_embedding
    ON chunk
    USING diskann (embedding)
    WHERE (indexed = true)
```

(The `indexed = true` condition is for easily bringing rows into and out of the index.)

## Fresh Index

```sql
SELECT pg_size_pretty(pg_relation_size('ix_chunk_embedding')) AS index_size;
 index_size 
------------
 24 kB
(1 row)
```

## Add rows to index

```sql
UPDATE chunk
SET indexed = true
WHERE id IN [... 500 ids ...];
```

This takes 4.1 seconds. The only reason why i'm doing `indexed = true`, is so that appending rows to the database doesn't take forever.

## Check Index size again

```sql
SELECT pg_size_pretty(pg_relation_size('ix_chunk_embedding')) AS index_size;
 index_size 
------------
 4024 kB
(1 row)
```

## Reindex

```sql
REINDEX INDEX ix_chunk_embedding;
```

This runs almost instantly (<100ms?)

```sql
SELECT pg_size_pretty(pg_relation_size('ix_chunk_embedding')) AS index_size;
 index_size 
------------
 352 kB
(1 row)
```

And it's over 10x smaller.

---

My issue is that incremental updates are both incredibly slow, and also not space efficient. Is there a way to disable incremental indexing altogether? I don't mind if incrementally indexed rows don't show up in recall, because I can just do `SET indexed = true` and then follow-up with a `REINDEX CONCURRENTLY`. Right now, I have no efficient way to do this.

Theoretically, there should be ways to make updates should be more efficient (MSFT advertises 1000 QPS and sub-ms latency for inserts https://youtu.be/BnYNdSIKibQ?t=352), but even then a `SET LOCAL diskann_suppress_indexing = on;` to disable INSERT/UPDATE indexing would still be useful. Drop+Recreate doesn't work because then queries stop working.

**Comment by syvb** [comment]
Yes, this should be fixed on the latest version.

@npip99 I'm closing this issue but if you can still replicate it, please reopen.
