### ISSUE TITLE
pgvecto-rs: How does pgvectorscale compare to pgvecto-rs? Where pgvecto-rs is also built with Rust and pgrx.

### ISSUE THREAD

**Issue by Miuler** [timescale/pgvectorscale#133]
How does pgvectorscale compare to pgvecto-rs? Where pgvecto-rs is also built with Rust and pgrx.

**Comment by saolof** [comment]
Different set of indexes. Pgvectorscale adds disk-friendly indexes, while pgvecto-rs seems to add more functionality around existing pgvector index types
