### ISSUE TITLE
Set up Pgvectorscale on Azure Postgres Flexible Server

### ISSUE THREAD

**Issue by baniasbaabe** [timescale/pgvectorscale#138]
Is there any possibility to manually set up pgvectorscale extension on an Azure Postgres Flexible Server? Curious to know since pgvectorscale isn‘t in Azures Extension list yet. 

Thanks for the great library :)!

**Comment by alejandrodnm** [comment]
You can only install the pre-approved extensions from: [Postgres Flexible Service extensions](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-extensions#extension-versions).

I found this comment

https://github.com/MicrosoftDocs/azure-docs/issues/112207#issuecomment-2180250397

> If there is some extension you would like us to incorporate in the service and is not there yet, please go to https://aka.ms/PGFeedback, search if somebody asked for it already and vote for it, or create a new idea in that forum so that others can find it and vote for it. We triage those regularly to plan and prioritize work items in our backlog.

Thanks :)
