### ISSUE TITLE
Maximum dimensions CONCURRENTLY 

### ISSUE THREAD

**Issue by SlaveRHNH** [timescale/pgvectorscale#142]
app=# CREATE INDEX CONCURRENTLY idx_vectors_embeddings on vectors using diskann (feature_vector);
NOTICE:  Starting index build. num_neighbors=-1 search_list_size=100, max_alpha=1.2, storage_layout=SbqCompression
ERROR:  assertion failed: dimensions > 0 && dimensions < 2000

Сould you change the maximum dimensions from 1999 to 2000?

**Comment by SlaveRHNH** [comment]
Hello! I wanted to kindly check if there might be any updates on this issue. Thank you very much!

**Comment by cevian** [comment]
@SlaveRHNH this should go out in the next release
